development:
  sendgrid:
    key: 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

production:
  sendgrid:
    key: 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
